---
- hosts: web
  tasks:
    - name: Template a file to /var/www/html/index.html
      template:
        src: index.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'